export type WsLocale = "en" | "fa";

const EN = {
  inbox: "Inbox",
  tracker: "Tracker",
  chat: "Chat",
  documents: "Documents",
  office: "Office",
  tasksNav: "Tasks",
  docNav: "Doc",
  calendar: "Calendar",
  search: "Search",
  issues: "Issues",
  backlog: "Backlog",
  active: "In progress",
  activeNow: "Active",
  board: "Board",
  newChannel: "New channel",
  newDm: "Direct message",
  invite: "Invite",
  workspace: "Studio",
  light: "Light",
  dark: "Dark",
  activity: "What moved in Tracker, Chat, and Office.",
  unread: "Unread",
  all: "All",
  files: "Files",
  mentions: "Mentions",
  presence: "In room",
  lobby: "In office",
  createIssue: "Create issue",
  emptyIssuesTitle: "No issues yet",
  emptyIssuesBody: "Capture the next cut, upload, or review so the studio has a single queue.",
  emptyBacklogTitle: "Backlog is clear",
  emptyBacklogBody: "Park work here before it is in progress.",
  emptyActiveTitle: "Nothing in progress",
  emptyActiveBody: "Move an issue here when someone is actively shooting or editing.",
  emptyInboxTitle: "Inbox is quiet",
  emptyInboxBody: "New issues, mentions, and rooms will land here.",
  emptyChatTitle: "Pick a channel",
  emptyChatBody: "Open a space in the navigator, or start a direct message.",
  emptyDocsTitle: "No documents",
  emptyDocsBody: "Write a brief, shot list, or cut notes and link them to an issue.",
  emptyOfficeTitle: "No rooms",
  emptyOfficeBody: "Create a room for dailies, client review, or a quick standup.",
  emptyCalendarTitle: "Nothing scheduled",
  emptyCalendarBody: "Office rooms appear here by day once they have a start time.",
  emptyChannelTitle: "No messages yet",
  emptyChannelBody: "Say what you are cutting, blocking, or waiting on.",
  admin: "Admin",
  collaborator: "Collaborator",
  member: "Member",
  lightMode: "Light mode",
  darkMode: "Dark mode",
  projects: "Projects",
  profile: "Profile",
  account: "Account",
  chatSettings: "Chat settings",
  privacy: "Privacy & Security",
  notifications: "Notifications",
  data: "Data",
  devices: "Devices",
  language: "Language",
  accounts: "Accounts",
  settings: "Settings",
  you: "You",
  youBadge: "You",
  logOut: "Log out",
  close: "Close",
  back: "Back",
  more: "More",
  changePhoto: "Change photo",
  photoHint: "Tap photo to upload a new image (max 5MB).",
  displayName: "Display name",
  username: "Username",
  email: "Email",
  bio: "Bio",
  saveAccount: "Save account",
  saving: "Saving…",
  saved: "Saved",
  save: "Save",
  saveFailed: "Could not save",
  sendEnter: "Send with Enter",
  messageSounds: "Message sounds",
  compactMessages: "Compact messages",
  readReceipts: "Read receipts",
  anyoneDm: "Anyone can start a DM",
  password: "Password",
  newPassword: "New password",
  repeatPassword: "Repeat password",
  updatePassword: "Update password",
  passwordMismatch: "Passwords do not match",
  passwordUpdated: "Password updated",
  passwordFailed: "Password was not updated",
  inboxActivity: "Inbox activity",
  mentionAlerts: "Mentions",
  taskAlerts: "Tasks",
  meetingAlerts: "Meetings",
  downloadData: "Download my workspace data",
  clearCache: "Clear local cache",
  cacheCleared: "Local workspace cache cleared",
  thisBrowser: "This browser",
  onlineYes: "Online: yes",
  onlineNo: "Online: no",
  photoFailed: "Photo could not be updated (max 5MB)",
  tv: "TV",
  share: "Share",
  mute: "Mute",
  unmute: "Unmute",
  stopVideo: "Stop video",
  startVideo: "Start video",
  leave: "Leave",
  docs: "Docs",
  nothingOnTv: "Nothing on TV",
  reminder: "Reminder",
  noReminders: "No reminders",
  goLive: "Go live",
  clear: "Clear",
  file: "File",
  open: "Open",
  closeShare: "Close",
  uploadFile: "Upload any file",
  noFiles: "No files yet",
  pickRoom: "Pick a room to join the call. Camera stays off until you enter.",
  roomName: "Room name",
  newRoom: "New room",
  noOneOnline: "No one online",
  guest: "Guest",
  newProject: "New project",
  newDocument: "New document",
  rooms: "Rooms",
  apps: "Apps",
  done: "Done",
  unassigned: "Unassigned",
  newIssue: "New issue",
  description: "Description",
  labels: "labels, comma separated",
  addSubIssue: "Add sub-issue",
  comment: "Comment",
  untitled: "Untitled",
  docsHint: "Type / for heading, list, or issue link…",
  heading: "Heading",
  bulletList: "Bullet list",
  linkIssue: "Link issue",
  online: "online",
  callRoom: "Room",
  callMeeting: "Meeting",
  chats: "Chats",
  viewAll: "View all",
  pv: "PV",
  groups: "Groups",
  bots: "Bots",
  newChat: "New chat",
  unreadOnly: "Unread only",
  noChats: "No chats yet",
  noChatsBody: "Start a private message from the plus button.",
  noBots: "No bots yet",
  noBotsBody: "Workspace bots will appear here.",
  messagePlaceholder: "Message",
  send: "Send",
  reply: "Reply",
  thread: "Thread",
  voice: "Voice",
  stop: "Stop",
  sharedFile: "Shared a file",
  voiceNote: "Voice note",
  filters: "Filters",
  loadEarlier: "Load earlier",
  people: "Team",
  lock: "Lock",
  unlock: "Unlock",
  deactivate: "Deactivate",
  activate: "Activate",
  due: "Due",
  progress: "Progress",
  requestTime: "Ask for more time",
  extraTime: "Extra hours",
  pending: "Pending",
  approved: "Approved",
  denied: "Denied",
  addEvent: "Add event",
  countdown: "Countdown",
  personalRoom: "My room",
  projectRoom: "Project room",
  requestJoin: "Ask to join",
  waiting: "Waiting for approval",
  allow: "Allow",
  deny: "Deny",
  offline: "Offline",
  performance: "Task score",
  attendance: "Call presence",
  upload: "Upload",
  locked: "Locked",
  inactive: "Inactive",
  manager: "Manager",
  subtask: "Subtask",
  markDone: "Done",
  myTasks: "My tasks",
  boardNotes: "Board",
  hours: "hours",
  noProjects: "No projects yet",
  noProjectsBody: "Create a project to open its chat, files, tasks, and room.",
  collaborators: "Collaborators",
  message: "Message",
  openRoom: "Open my room",
  closeRoom: "Close my room",
  joinRequests: "Join requests",
  roomClosed: "This room is closed",
  dedicatedRoom: "Dedicated room",
  newDedicatedRoom: "New dedicated room",
};

const FA: typeof EN = {
  inbox: "صندوق",
  tracker: "پیگیری",
  chat: "گفتگو",
  documents: "اسناد",
  office: "دفتر",
  tasksNav: "تسک‌ها",
  docNav: "اسناد",
  calendar: "تقویم",
  search: "جستجو",
  issues: "مسئله‌ها",
  backlog: "بک‌لاگ",
  active: "در حال انجام",
  activeNow: "فعال",
  board: "بورد",
  newChannel: "کانال جدید",
  newDm: "پیام مستقیم",
  invite: "دعوت",
  workspace: "استودیو",
  light: "روشن",
  dark: "تیره",
  activity: "حرکت‌ها در پیگیری، گفتگو و دفتر.",
  unread: "نخوانده",
  all: "همه",
  files: "فایل‌ها",
  mentions: "منشن",
  presence: "در اتاق",
  lobby: "در دفتر",
  createIssue: "ساخت مسئله",
  emptyIssuesTitle: "هنوز مسئله‌ای نیست",
  emptyIssuesBody: "کار بعدی فیلمبرداری، آپلود یا بازبینی را اینجا ثبت کنید.",
  emptyBacklogTitle: "بک‌لاگ خالی است",
  emptyBacklogBody: "کار را قبل از شروع اینجا نگه دارید.",
  emptyActiveTitle: "کاری در جریان نیست",
  emptyActiveBody: "وقتی کسی مشغول تدوین یا فیلمبرداری است، مسئله را به اینجا ببرید.",
  emptyInboxTitle: "صندوق ساکت است",
  emptyInboxBody: "مسئله، منشن و اتاق جدید اینجا می‌آید.",
  emptyChatTitle: "یک کانال انتخاب کنید",
  emptyChatBody: "از ناوبری یک فضا باز کنید، یا پیام مستقیم بسازید.",
  emptyDocsTitle: "سندی نیست",
  emptyDocsBody: "بریف، شات‌لیست یا نت برش بنویسید و به مسئله وصل کنید.",
  emptyOfficeTitle: "اتاقی نیست",
  emptyOfficeBody: "برای دایلیز، بازبینی مشتری یا استندآپ اتاق بسازید.",
  emptyCalendarTitle: "زمان‌بندی خالی است",
  emptyCalendarBody: "اتاق‌های دفتر بعد از داشتن زمان شروع اینجا دیده می‌شوند.",
  emptyChannelTitle: "پیامی نیست",
  emptyChannelBody: "بگویید چه چیزی در حال برش، بلاک یا انتظار است.",
  admin: "ادمین",
  collaborator: "همکار",
  member: "عضو",
  lightMode: "حالت روشن",
  darkMode: "حالت تیره",
  projects: "پروژه‌ها",
  profile: "پروفایل",
  account: "حساب",
  chatSettings: "تنظیمات گفتگو",
  privacy: "حریم خصوصی و امنیت",
  notifications: "اعلان‌ها",
  data: "داده‌ها",
  devices: "دستگاه‌ها",
  language: "زبان",
  accounts: "حساب‌ها",
  settings: "تنظیمات",
  you: "شما",
  youBadge: "شما",
  logOut: "خروج",
  close: "بستن",
  back: "بازگشت",
  more: "بیشتر",
  changePhoto: "تغییر عکس",
  photoHint: "برای آپلود تصویر جدید روی عکس بزنید (حداکثر ۵ مگابایت).",
  displayName: "نام نمایشی",
  username: "نام کاربری",
  email: "ایمیل",
  bio: "بیو",
  saveAccount: "ذخیره حساب",
  saving: "در حال ذخیره…",
  saved: "ذخیره شد",
  save: "ذخیره",
  saveFailed: "ذخیره نشد",
  sendEnter: "ارسال با Enter",
  messageSounds: "صدای پیام",
  compactMessages: "پیام فشرده",
  readReceipts: "رسید خوانده‌شدن",
  anyoneDm: "هر کس بتواند پیام مستقیم بزند",
  password: "رمز عبور",
  newPassword: "رمز جدید",
  repeatPassword: "تکرار رمز",
  updatePassword: "به‌روزرسانی رمز",
  passwordMismatch: "رمزها یکی نیستند",
  passwordUpdated: "رمز به‌روز شد",
  passwordFailed: "رمز به‌روز نشد",
  inboxActivity: "فعالیت صندوق",
  mentionAlerts: "منشن",
  taskAlerts: "تسک‌ها",
  meetingAlerts: "جلسات",
  downloadData: "دانلود داده‌های ورک‌اسپیس",
  clearCache: "پاک کردن کش محلی",
  cacheCleared: "کش محلی پاک شد",
  thisBrowser: "این مرورگر",
  onlineYes: "آنلاین: بله",
  onlineNo: "آنلاین: خیر",
  photoFailed: "عکس به‌روز نشد (حداکثر ۵ مگابایت)",
  tv: "تیوی",
  share: "اشتراک",
  mute: "بی‌صدا",
  unmute: "با صدا",
  stopVideo: "قطع ویدیو",
  startVideo: "شروع ویدیو",
  leave: "خروج",
  docs: "اسناد",
  nothingOnTv: "چیزی روی تیوی نیست",
  reminder: "یادآور",
  noReminders: "یادآوری نیست",
  goLive: "پخش زنده",
  clear: "پاک کردن",
  file: "فایل",
  open: "باز کردن",
  closeShare: "بستن",
  uploadFile: "آپلود فایل",
  noFiles: "فایلی نیست",
  pickRoom: "یک اتاق را برای ورود به تماس انتخاب کنید. دوربین تا ورود خاموش می‌ماند.",
  roomName: "نام اتاق",
  newRoom: "اتاق جدید",
  noOneOnline: "کسی آنلاین نیست",
  guest: "مهمان",
  newProject: "پروژه جدید",
  newDocument: "سند جدید",
  rooms: "اتاق‌ها",
  apps: "برنامه‌ها",
  done: "انجام‌شده",
  unassigned: "بدون مسئول",
  newIssue: "مسئله جدید",
  description: "توضیح",
  labels: "برچسب‌ها، جدا با ویرگول",
  addSubIssue: "زیرمسئله",
  comment: "نظر",
  untitled: "بدون عنوان",
  docsHint: "برای تیتر، لیست یا لینک مسئله / بزنید…",
  heading: "تیتر",
  bulletList: "لیست نقطه‌ای",
  linkIssue: "لینک مسئله",
  online: "آنلاین",
  callRoom: "اتاق",
  callMeeting: "جلسه",
  chats: "گفتگوها",
  viewAll: "مشاهده همه",
  pv: "خصوصی",
  groups: "گروه‌ها",
  bots: "ربات‌ها",
  newChat: "گفتگوی جدید",
  unreadOnly: "فقط نخوانده",
  noChats: "هنوز گفتگویی نیست",
  noChatsBody: "با دکمه به‌علاوه یک پیام خصوصی شروع کنید.",
  noBots: "رباتی نیست",
  noBotsBody: "ربات‌های ورک‌اسپیس اینجا دیده می‌شوند.",
  messagePlaceholder: "پیام",
  send: "ارسال",
  reply: "پاسخ",
  thread: "رشته",
  voice: "صدا",
  stop: "توقف",
  sharedFile: "فایل فرستاد",
  voiceNote: "پیام صوتی",
  filters: "فیلتر",
  loadEarlier: "پیام‌های قبلی",
  people: "تیم",
  lock: "قفل",
  unlock: "باز کردن",
  deactivate: "غیرفعال",
  activate: "فعال",
  due: "موعد",
  progress: "پیشرفت",
  requestTime: "درخواست زمان بیشتر",
  extraTime: "ساعت اضافه",
  pending: "در انتظار",
  approved: "تأیید شد",
  denied: "رد شد",
  addEvent: "افزودن رویداد",
  countdown: "شمارش معکوس",
  personalRoom: "اتاق من",
  projectRoom: "اتاق پروژه",
  requestJoin: "درخواست ورود",
  waiting: "منتظر تأیید",
  allow: "اجازه",
  deny: "رد",
  offline: "آفلاین",
  performance: "عملکرد تسک",
  attendance: "حضور در تماس",
  upload: "آپلود",
  locked: "قفل",
  inactive: "غیرفعال",
  manager: "مدیر",
  subtask: "زیرتسک",
  markDone: "انجام شد",
  myTasks: "تسک‌های من",
  boardNotes: "برد",
  hours: "ساعت",
  noProjects: "هنوز پروژه‌ای نیست",
  noProjectsBody: "با ساخت پروژه، چت، فایل، تسک و اتاق آن باز می‌شود.",
  collaborators: "همکاران",
  message: "پیام",
  openRoom: "باز کردن اتاق من",
  closeRoom: "بستن اتاق من",
  joinRequests: "درخواست ورود",
  roomClosed: "این اتاق بسته است",
  dedicatedRoom: "اتاق اختصاصی",
  newDedicatedRoom: "اتاق اختصاصی جدید",
};

export function wsCopy(locale: WsLocale) {
  return locale === "fa" ? FA : EN;
}

export function wsDateLocale(locale: WsLocale) {
  return locale === "fa" ? "fa-IR" : "en-US";
}
