export type WsLocale = "en" | "fa";

const EN = {
  inbox: "Inbox",
  tracker: "Tracker",
  chat: "Chat",
  documents: "Documents",
  office: "Office",
  tasksNav: "Tasks",
  docNav: "Doc",
  calendar: "Calendar",
  search: "Search",
  issues: "Issues",
  backlog: "Backlog",
  active: "In progress",
  board: "Board",
  newChannel: "New channel",
  newDm: "Direct message",
  invite: "Invite",
  workspace: "Studio",
  light: "Light",
  dark: "Dark",
  activity: "What moved in Tracker, Chat, and Office.",
  unread: "Unread",
  all: "All",
  files: "Files",
  mentions: "Mentions",
  presence: "In room",
  lobby: "In office",
  createIssue: "Create issue",
  emptyIssuesTitle: "No issues yet",
  emptyIssuesBody: "Capture the next cut, upload, or review so the studio has a single queue.",
  emptyBacklogTitle: "Backlog is clear",
  emptyBacklogBody: "Park work here before it is in progress.",
  emptyActiveTitle: "Nothing in progress",
  emptyActiveBody: "Move an issue here when someone is actively shooting or editing.",
  emptyInboxTitle: "Inbox is quiet",
  emptyInboxBody: "New issues, mentions, and rooms will land here.",
  emptyChatTitle: "Pick a channel",
  emptyChatBody: "Open a space in the navigator, or start a direct message.",
  emptyDocsTitle: "No documents",
  emptyDocsBody: "Write a brief, shot list, or cut notes and link them to an issue.",
  emptyOfficeTitle: "No rooms",
  emptyOfficeBody: "Create a room for dailies, client review, or a quick standup.",
  emptyCalendarTitle: "Nothing scheduled",
  emptyCalendarBody: "Office rooms appear here by day once they have a start time.",
  emptyChannelTitle: "No messages yet",
  emptyChannelBody: "Say what you are cutting, blocking, or waiting on.",
};

const FA: typeof EN = {
  inbox: "صندوق",
  tracker: "پیگیری",
  chat: "گفتگو",
  documents: "اسناد",
  office: "دفتر",
  tasksNav: "تسک‌ها",
  docNav: "اسناد",
  calendar: "تقویم",
  search: "جستجو",
  issues: "مسئله‌ها",
  backlog: "بک‌لاگ",
  active: "در حال انجام",
  board: "بورد",
  newChannel: "کانال جدید",
  newDm: "پیام مستقیم",
  invite: "دعوت",
  workspace: "استودیو",
  light: "روشن",
  dark: "تیره",
  activity: "حرکت‌ها در پیگیری، گفتگو و دفتر.",
  unread: "نخوانده",
  all: "همه",
  files: "فایل‌ها",
  mentions: "منشن",
  presence: "در اتاق",
  lobby: "در دفتر",
  createIssue: "ساخت مسئله",
  emptyIssuesTitle: "هنوز مسئله‌ای نیست",
  emptyIssuesBody: "کار بعدی فیلمبرداری، آپلود یا بازبینی را اینجا ثبت کنید.",
  emptyBacklogTitle: "بک‌لاگ خالی است",
  emptyBacklogBody: "کار را قبل از شروع اینجا نگه دارید.",
  emptyActiveTitle: "کاری در جریان نیست",
  emptyActiveBody: "وقتی کسی مشغول تدوین یا فیلمبرداری است، مسئله را به اینجا ببرید.",
  emptyInboxTitle: "صندوق ساکت است",
  emptyInboxBody: "مسئله، منشن و اتاق جدید اینجا می‌آید.",
  emptyChatTitle: "یک کانال انتخاب کنید",
  emptyChatBody: "از ناوبری یک فضا باز کنید، یا پیام مستقیم بسازید.",
  emptyDocsTitle: "سندی نیست",
  emptyDocsBody: "بریف، شات‌لیست یا نت برش بنویسید و به مسئله وصل کنید.",
  emptyOfficeTitle: "اتاقی نیست",
  emptyOfficeBody: "برای دایلیز، بازبینی مشتری یا استندآپ اتاق بسازید.",
  emptyCalendarTitle: "زمان‌بندی خالی است",
  emptyCalendarBody: "اتاق‌های دفتر بعد از داشتن زمان شروع اینجا دیده می‌شوند.",
  emptyChannelTitle: "پیامی نیست",
  emptyChannelBody: "بگویید چه چیزی در حال برش، بلاک یا انتظار است.",
};

export function wsCopy(locale: WsLocale) {
  return locale === "fa" ? FA : EN;
}
